The first question:
Why does this fail like so?
```
nathan@chonky:~/src/rust-questions/sqlite-question-one
$ cargo run
   Compiling sqlite-question-one v0.1.0 (/Users/nathan/src/rust-questions/sqlite-question-one)
error[E0505]: cannot move out of `connection` because it is borrowed
  --> src/main.rs:15:5
   |
12 |     let mut statement = connection.prepare("SELECT * FROM hello_world;").unwrap();
   |                         ------------------------------------------------ borrow of `connection` occurs here
...
15 |     connection
   |     ^^^^^^^^^^ move out of `connection` occurs here
16 | }
   | - borrow might be used here, when `statement` is dropped and runs the `Drop` code for type `Statement`

For more information about this error, try `rustc --explain E0505`.
error: could not compile `sqlite-question-one` due to previous error
Last command had exit code: 101 at 06:24
nathan@chonky:~/src/rust-questions/sqlite-question-one
$
```